### ISSUE TITLE
MULTIPLAYER: DBT hairs do not show up to other players

### ISSUE THREAD

**Issue by LinkatriX** [dbtr/DBT#102]
**Describe the bug**
Selecting a dbt hair of any kind does not display selected hair on the other player's screen. It will instead show their default hair from character creation.

**To Reproduce**
Step 1: Be on multiplayer with others.
Step 2: Have dbt hair set
Step 3: They observe

**Screenshots**
N/A
**Other Mods**
N/A

**Additional Info**
N/A

**Comment by Tyndareus** [comment]
Fixed, including colours but not dye, will do dye another time
