### ISSUE TITLE
Game crash when reloading work

### ISSUE THREAD

**Issue by eshayunit** [dbtr/DBT#107]
**Describe the bug**
The game crashed when I reloaded the world

**To Reproduce**
[client.log](https://github.com/dbtr/DBT/files/4970552/client.log)

I unloaded several mods before joining, that may be an issue.

1: close terraria
2: unload several mods
3: relog

**Screenshots**
![image](https://user-images.githubusercontent.com/68727928/88367995-6fc08100-cdd0-11ea-9018-74411629639c.png)

**Other Mods**

There are all the mods I had installed at the time:
Boss checklist
Boss cursor 
Cheat sheet
DBZMOD
Dynascape
Elemental Hearts
Fargo souls mod
Magic storage
Recipe 
Universe of bows
Vein miner
Very short respawn time
Wing slot
What mod is this from

**Additional Info**
None

**Comment by Tyndareus** [comment]
Fixed
