### ISSUE TITLE
Overloaded Legendary trait Ki bar issue

### ISSUE THREAD

**Issue by RustandSalt** [dbtr/DBT#109]
**Describe the bug**
The Ki bar does not display actual numbers but rather random letters when one uses SSJ/C-type, SSJ/A-type or LSSJ after it overloads.

**To Reproduce**
1. Turn LSSJ/ SSJA/ SSJC.
2. Wait for overload.
3. Look at Ki Bar.

**Screenshots**
![Nicew](https://user-images.githubusercontent.com/68740966/88395488-bd9ab080-cdf3-11ea-8ceb-10b36aa78fbe.gif)

**Other Mods**
Boss Checklist, HERO's Mod, Cheat Sheet, Recipe Browser, Potion Charms

**Additional Info**
Tried with multiple different characters.

**Comment by FullNovaAlchemist** [comment]
Intended
