### ISSUE TITLE
Night time stays after Shenron summon

### ISSUE THREAD

**Issue by Raiden216** [dbtr/DBT#111]
**Description**
Once Shenron gets summoned, time skips forward, but doesn't revert to what it was before summoning.

**To Reproduce:**
Summon Shenron

[client.log](https://github.com/dbtr/DBT/files/4972690/client.log)
)

**Screenshots**
![image](https://user-images.githubusercontent.com/68744497/88404170-f4b69500-cde6-11ea-9f96-e32d3b26365e.png)

![image](https://user-images.githubusercontent.com/68744497/88404249-144dbd80-cde7-11ea-8843-9f1ca06e2a2e.png)

![image](https://user-images.githubusercontent.com/68744497/88404275-1adc3500-cde7-11ea-9f14-38004c70ef52.png)

**Other Mods**
N/A

**Additional Info**
Add any other context or information about the problem here.

**Comment by Tyndareus** [comment]
Fixed
