### ISSUE TITLE
transformation sprite stays

### ISSUE THREAD

**Issue by ProfessorDaDUu** [dbtr/DBT#113]
when transforming into any form and removing the "buff" by right clicking it you will cancel the transformation but the 
sprite for the transformation will stay

1. transform into any form 
2. remove the "transformation buff" below your hotbar

![image](https://user-images.githubusercontent.com/68728907/88421518-fed99300-cde8-11ea-874d-781dcab8464d.png)

**Comment by Tyndareus** [comment]
Fixed
