### ISSUE TITLE
Potential unleashed/ potential unlocked changes hair color

### ISSUE THREAD

**Issue by ProfessorDaDUu** [dbtr/DBT#114]
Potential unlocked and potential unleashed turn your hair and tail color into orange

to replicate:
1. load world
2. transform into said form
3. look at hair

![image](https://user-images.githubusercontent.com/68728907/88423524-2f6efc00-cdec-11ea-92a3-377fe361ba4b.png)

**Comment by Tyndareus** [comment]
Fixed for ... whatever build is next
