### ISSUE TITLE
Clicking on form icons on the forms menu creates lag

### ISSUE THREAD

**Issue by Lefucker** [dbtr/DBT#118]
**Describe the bug**
Clicking on the form icons in the transformation menu builds up lag that appears whenever you're in said menu.

**To Reproduce**
Repeatedly click transformation icons until you start noticing your frames getting smaller and smaller.

**Screenshots**
N/A

**Other Mods**
Cheat sheet.

**Additional Info**
You can reset the accumulated lag by restarting terraria altogether.

**Comment by Tyndareus** [comment]
Temp fix
