### ISSUE TITLE
Removing armor doesn't reduce current ki.

### ISSUE THREAD

**Issue by GrismarPicklemelt** [dbtr/DBT#120]
**Describe the bug**
If you remove your current armor your max ki will be reduced accordingly but your current ki won't go down with it.
(I have seen something like this discussed but only with transformations and such, nothing about armor.)

**To Reproduce**
1. Equip an armor set (I used the Saiyan Battle armor set)
2. Remove the armor pieces
[client.log](https://github.com/dbtr/DBT/files/4973852/client.log)

**Screenshots**
![maxkiissuedbt](https://user-images.githubusercontent.com/45777238/88427295-a5f60480-cdc0-11ea-8660-bf717a884eba.png)

**Other Mods**
These are all the mods I had enabled:
Boss Checklist 1.1.3
Recipe Browser 0.8.7
Webmilio's Commons Library 0.1.13.1
Dragon Ball Terraria 1.1.0.0
Cheat Sheet 0.6.6
Magic Storage 0.4.3.5
VeinMiner 1.3.1
Full Health Respawn 0.0.1
Yet Another Boss Health Bar 1.3.2

**Additional Info**
-Leaving the world does not reset your ki.
-Changing Armor sets doesn't reset your ki.

When I saw this bug I was putting on lots of different armor sets, and I tested it more using the Saiyan Battle and Saiyan Scout sets. This may have been the cause but I'm not 100% sure.

**Comment by Tyndareus** [comment]
Fixed
