### ISSUE TITLE
Legendary Trait doesn't seem to give 2x Ki

### ISSUE THREAD

**Issue by Raiden216** [dbtr/DBT#137]
**Describe the bug**
After genetic reshuffling, it seems as if the Legendary Trait only gives you 500 Ki instead of 2x Ki.

**To Reproduce**
1. Be/Get Legendary trait
2. Take note of Ki
3. Wish for Genetic Reshuffle
4. Compare Ki with previous one

**Screenshots**
![image](https://user-images.githubusercontent.com/68744497/88459516-6eb25100-ceaf-11ea-837a-54ea87994ea4.png)

![image](https://user-images.githubusercontent.com/68744497/88459542-a3260d00-ceaf-11ea-8dbd-55d53a4ee0b5.png)

**Other Mods**
N/A

**Additional Info**
On the character, I've gained a lot of Ki through fighting and through power wishes, which is why it's as high as it is.
[client.log](https://github.com/dbtr/DBT/files/4975721/client.log)

**Comment by Tyndareus** [comment]
Fixed but it will only apply to your own ki, not including any armors/accessories that add to it.
