### ISSUE TITLE
Using vodoo doll to kill guide is able to unlock ssj

### ISSUE THREAD

**Issue by LinkatriX** [dbtr/DBT#141]
**Describe the bug**
If the player throws the guide voodoo doll into lava while having enough ki and friendship with guide, they will go ssj1 if it is not already unlocked.

**To Reproduce**
Step 1: Meet ssj1 unlock requirements (must be friends with guide).
Step 2: Throw guide voodoo doll in lava
Step 3: Observe

**Comment by Tyndareus** [comment]
Fixed
