### ISSUE TITLE
fps drops when opening transformation menu

### ISSUE THREAD

**Issue by ProfessorDaDUu** [dbtr/DBT#143]
whenever I open the transformation menu i get huge frame drops (max being 33 fps) the lags will only occur if you repeatedly press (select) a transformation from the menu

to reproduce: 
1.load world 
2.open transformation menu
3. repeatedly click an a transformation 

mods used: DBT, webmilios commons library, heros mod. cheat sheet

**Comment by Tyndareus** [comment]
Temp fix
