### ISSUE TITLE
charge flying makes you slower

### ISSUE THREAD

**Issue by ProfessorDaDUu** [dbtr/DBT#150]
when charge flying with a certain transformation active you will become slower instead of faster
forms affected are:ssj4 full power, every god form (ssjg,super sayian c type,evil super sayian 3 speed dont change at all) , LSSJ, evil super sayian 3 full power, PU2
to recreate:
1.load world
2. get a cellphone or stopwatch (to see speed)
3. select one of the transformations
4.charge fly

**Comment by Tyndareus** [comment]
https://github.com/dbtr/DBT/issues/83

may have been related
should be fixed now since the charge checks against flying
