### ISSUE TITLE
Saiyan Elite armor causing nearly infinite transformation time.

### ISSUE THREAD

**Issue by GrismarPicklemelt** [dbtr/DBT#153]
**Describe the bug**
If you were to equip your character with the Saiyan Elite armor set and transform into any form, the natural regen would cause you to stay in the transformed state with at least 2 ki. While you are like this you cannot fire ki blasts, and flying will cause you to fall out of the transformed state.

**To Reproduce**
1a. Equip any character with the Saiyan Elite armor, even one with no items or boosts at all.
1b. Having over 16k maximum ki also seems to have the same effect as the Saiyan Elite Armor *(Discovered by Tyndareus.)
2. Transform, any form will work. Even SSJBEvo.
3. Wait for your ki to run out, don't use ki attacks or you will revert to base.
4. Once you run out of ki you will stall at 2 or more ki (depending on your max), you can't use ki moves while like this but you still get the speed and the defense boost.

**Screenshots**
![20200727131302_1](https://user-images.githubusercontent.com/45777238/88571058-0f695380-d00b-11ea-9f44-1423a520f1b4.jpg)

**Other Mods**
These are all the mods I had enabled:
Boss Checklist 1.1.3
Recipe Browser 0.8.7
Webmilio's Commons Library 0.1.13.1
Dragon Ball Terraria 1.1.0.0
Cheat Sheet 0.6.6
Magic Storage 0.4.3.5
VeinMiner 1.3.1
Full Health Respawn 0.0.1
Yet Another Boss Health Bar 1.3.2

**Additional Info**
Sometimes you will randomly fall out of the form, this is rare and there doesn't seem to be any constant for it.

*Initially we thought that removing the armor didn't remove the forms, but it turns out that it was just having your ki over 16k as discovered by Tyndareus.

**Comment by Tyndareus** [comment]
Fixed
