### ISSUE TITLE
Can't restore ki while flying

### ISSUE THREAD

**Issue by ProfessorDaDUu** [dbtr/DBT#158]
Remeber how you used to be able to restore ki while flying by charging mid air and standing still.
now if you try to charge mid air while not moving it drains as much ki as it would when charge flying (accilerating).
though im not sure if its intended im still going to report it
 
to reproduce:
1.load world
2.fly 
3.charge while flying and dont move
4. look at ki

**Comment by Tyndareus** [comment]
Fixed, though the ki restoration is still based on your own regen, if the flight drain is more than you can regen you obviously still drain just slower
