### ISSUE TITLE
Doubling the skills (although its useless)

### ISSUE THREAD

**Issue by TheCyrax** [dbtr/DBT#161]
**Describe the bug**
If you put equipped skill in the trash can and then double click on the equip (or unequip, its broken and sometimes doesn't change, refer to my previous issue), it will give you a copy of this skill.

**To Reproduce**
1. Equip a skill
2. Put the skill in the trash can in your inventory
3. Double click on the equip button
4. Get the skill out of the trash can
5. You got two same skills

**Screenshots**
![image](https://user-images.githubusercontent.com/68279661/91437007-d7f00000-e871-11ea-81cf-d420ffa525ca.png)

**Other Mods**
N/A

**Additional Info**
I found this after i found my previous issue

**Comment by TheCyrax** [comment]
I also managed to get 4 skills now instead of three with the same method
![image](https://user-images.githubusercontent.com/68279661/91437275-4df46700-e872-11ea-82e9-274da7d5449b.png)

**Comment by Tyndareus** [comment]
Fixed, trash is considered a different inventory so the normal checking isn't good enough
