### ISSUE TITLE
New Shenron glitch

### ISSUE THREAD

**Issue by ProfessorDaDUu** [dbtr/DBT#162]
This all depends on WHEN you use the dragon balls  ( day or night)

When you use the dragon balls it will turn the opposite time ( when used on day it will turn night and the other way around)
after youve made your wish the daytime will return back to the one you started with, depending on which one it was it will be 4:30am or 7:30pm. After youve made the wish time will also move 3 times faster than usual until the night/day is over. When the night/day is over you will now see how everything escalate. So basically whats happening is that the game is starting a new night again and again. The chat is gonna be filled with "The bloodmoon is rising". If you have a cellphone and you look at the moon cycle you will see how it keeps changing. This will go on forever until you reload the world .

to recreate:
1:load world
1.1(optional):get a cellphone so you can see the moon cycle
2. summon shenron ( now your time will change for the first time)
3.make your wish (time will change back, time will move 3 times faster)
4. once the day or night is over you should see: chat messages, time will stand still, moon cycle will go crazy

**Comment by Tyndareus** [comment]
Fixed, shenron no longer controls time
