### ISSUE TITLE
Transformation Reshuffle and Aura Bug

### ISSUE THREAD

**Issue by zszeta** [dbtr/DBT#164]
**Describe the bug**
Previous trait form stays with new trait after reshuffle. Transform into any form in new trait, then transforming up will put you in your previous trait's form. After attempting to transform down, the transformation aura bugs and freezes in one frame, and the character is bugged.

**To Reproduce**
1) Have a trait and be in a form
2) Reshuffle with Shenron
3) Transform into any form
4) Transform up 
5) Transform down to observe animation bug

**Screenshots**
https://streamable.com/n1fsak

![fdgd](https://user-images.githubusercontent.com/68525620/91645178-ca648280-e9f7-11ea-9d82-c528532911b7.png)

**Other Mods**
Boss Checklist

**Additional Info**
I assume the form you had on previous to reshuffling is the one that stays with new trait. I am not sure if this applies for every trait yet. The animation bug I am unsure of what exactly caused it.

**Comment by Tyndareus** [comment]
Fixed
