### ISSUE TITLE
Shenron summoning with cheats

### ISSUE THREAD

**Issue by BrokenWyvern** [dbtr/DBT#80]
**Describe the bug**
Shenron when summoned by NPC command menu generates light aura and nametag, but sprite doesn't appear
**To Reproduce**
N/A

**Screenshots**
![Terraria_ Slimeassic Park 7_14_2020 2_53_24 PM](https://user-images.githubusercontent.com/64664491/87465163-32930c80-c5e2-11ea-9928-6d9ad5b49b70.png)

**Other Mods**
Hero's
**Additional Info**
Didn't have Dragon Balls when spawned, also made a wish with the latter prior to summoning

**Comment by NuovaPrime** [comment]
This isn't really something we can fix, nor do we want to fix, cheaters losing 💯
