### ISSUE TITLE
Teen Gohan Hair Crash

### ISSUE THREAD

**Issue by Northern-Newbie** [dbtr/DBT#82]
Using the Hair Selection 11 just outright crashes the Game.
It could be that i dont know if its supposed to be even implemented or not but choosing it crashes the Game whilst using Goku Hair works fine. 
At this point i havent tested other Hairs to see if it crashes too

ill add the Client Log although it looks like nothing really of rorth is in there
[client.log](https://github.com/dbtr/DBT/files/4921962/client.log)

Cause: Using Hair Selection 11

**Comment by Tyndareus** [comment]
https://github.com/dbtr/DBT/issues/107
Related.

Fixed.
