### ISSUE TITLE
Charging whilst walking does not reduce Speed

### ISSUE THREAD

**Issue by Northern-Newbie** [dbtr/DBT#83]
**Describe the bug**
Importance: 3
Walking and Charging doesnt reduce Walking Speed instead itll dipslay Runnning Particles and also play the Running Sound Effect yet not change Walk Speed

**To Reproduce**
Walk till you reach Full Speed then press and hold the Charge Button 

**Screenshots**
N/A

**Other Mods**
N/A

**Additional Info**
N/A

**Comment by Tyndareus** [comment]
Fixed
