### ISSUE TITLE
Super Kaioken aura duplication bug

### ISSUE THREAD

**Issue by LinkatriX** [dbtr/DBT#85]
**Describe the bug**
Super Kaioken spawns a separate aura a couple of blocks above the player

**To Reproduce**
Step 1: Select Super Kaioken in the transform menu
Step 2: Transform

**Screenshots**
![20200715141447_1](https://user-images.githubusercontent.com/60814556/87580885-1fe20b80-c6a6-11ea-98fa-7ae8eefaea03.jpg)

**Other Mods**
Hero Mod

**Additional Info**
N/A

**Comment by Skipping903** [comment]
Fixed on my branch, just an error with the number of frames in the code.
