### ISSUE TITLE
Importance 3: Getting hit during Overload "Cutscene" breaks it

### ISSUE THREAD

**Issue by Northern-Newbie** [dbtr/DBT#88]
**Describe the bug**
Getting during the "Cutscene" to activate Overload cancels and breaks it as in you dont get the Overload Feature yet the Ki Numbers still are scrambled 

**To Reproduce**
Set Transformation to any Forms with the Overload Feature and let the Overload Gauge fill during "Cutscene" get hit

**Screenshots**
N/A

**Other Mods**
N/A

**Additional Info**
Could reproduce it with various Enemys

**Comment by NuovaPrime** [comment]
Fixed with my next commit.
