### ISSUE TITLE
Importance: 5 - Stopwatch Flying/Walking Speed Miscalculation

### ISSUE THREAD

**Issue by zszeta** [dbtr/DBT#91]
**Describe the bug**
Walking speed shown on Stopwatch seems to be much faster than flying when transformed (in greater transformations). This doesn't really apply when not transformed.

**To Reproduce**
Wear Stopwatch, be transformed, preferably in a strong transformation (SSJ3+), and start normally walking/flying

**Screenshots**
_**Mute video, recorder doesn't usually record music lel**_
https://streamable.com/q1hbcj

**Other Mods**
Had Hero's Mod enabled at first, _but disabled it and the speed bug still existed_

**Additional Info**
The flying speed seems to drop lower and lower the more stronger the transformation is. For example, SSJ2 flying and walking speed difference isn't too great, but say in SSG, flight speed is greatly lower than walking speed. Also, SSJ3 walking speed flickers between 45 and 46

**Comment by zszeta** [comment]
I tried making a hyperlink to a streamables video, but it gone so here it is. https://streamable.com/q1hbcj

**Comment by NuovaPrime** [comment]
This is simply due to terraria's shitty code when it comes to the stopwatch, we can't do anything about this.
