### ISSUE TITLE
Shenron Bug

### ISSUE THREAD

**Issue by LinkatriX** [dbtr/DBT#95]
**Describe the bug**
Selecting and accepting the Next Transformation wish when you currently do not possess a transformation crashes the game

**To Reproduce**
Step 1: Summon Shenron
Step 2: Select Next Transformation wish
Step 3: Observe
[client.log](https://github.com/dbtr/DBT/files/4956753/client.log)
**Screenshots**
N/A

**Other Mods**
N/A

**Additional Info**
Add any other context or information about the problem here.

**Comment by Skipping903** [comment]
Lol we are not adding that progression breaking wish back in.
