### ISSUE TITLE
Divine trait's zenkai again 

### ISSUE THREAD

**Issue by TheCyrax** [dbtr/DBT#96]
**Describe the bug**
When you activate divine trait's passive which is zenkai and it ends, you gain the cooldown debuff. So i right clicked on it and it just disappeared. Its the same with the zenkai buff (but its okay prolly). So in the end you can use the passive almost without cooldown.

**To Reproduce**
1. Get Divine trait
2. Lower your health to less than 50%
3. Heal back to more than 50%
4. Wait until the ned of the buff
5. Right click the cooldown debuff icon

**Screenshots**
N/A

**Other Mods**
n/a

**Additional Info**
N/A

**Comment by Tyndareus** [comment]
Fixed
